console.log('welcome to simon');
//https://stackoverflow.com/questions/9419263/playing-audio-with-javascript was pointed in this direction by Jonathan G.

// variables that allow for selection of wedge/button
let pickWedge = document.querySelector('section');
// variables that create the sounds
let pickSoundGreen = new Audio('sounds/high-C-(green).mp3');
let pickSoundRed = new Audio('sounds/G-(red).mp3');
let pickSoundYellow = new Audio('sounds/E-(yellow).mp3');
let pickSoundBlue = new Audio('sounds/low-c-(blue).mp3');
let correctSound = new Audio('sounds/gliss-(correct).mp3');
let buzzSound = new Audio('sounds/buzz-(incorrect).mp3');
// variable for computer generated sequences
let computerSequence = [];

// allows for the player to select a box/button and the output is visual and auditory.
pickWedge.addEventListener('click', function (evt) {
    if (evt.target.className === 'wedge-choice1') {
        wedge('.wedge-choice1', '#30bb0b','#008000', pickSoundGreen);
    } else if (evt.target.className === 'wedge-choice2') {
        wedge('.wedge-choice2', '#FF0000', '#B22222', pickSoundRed);
    } else if (evt.target.className === 'wedge-choice3') {
        wedge('.wedge-choice3', '#FFFF00', '#ffc303', pickSoundYellow);
    } else if (evt.target.className === 'wedge-choice4') {
        wedge('.wedge-choice4', '#0000FF', '#00008B', pickSoundBlue);
    } else if (evt.target.className === 'simon') {
        // place hold the gliss sound and buzz sound
        correctSound.play();
        buzzSound.play();
    }
});
// a function to select a specific wedge/color/sound
function wedge(selector, highlight, color, audioObject) {
    document.querySelector(selector).style.backgroundColor = highlight;
    audioObject.play();
    setTimeout(() => {
        document.querySelector(selector).style.backgroundColor = color;
    }, 800);
}

// a function to generate a random number
function randomNumberBetween(num1, num2) {
    return Math.floor(Math.random() * (num2 - num1 + 1) + num1);
}
// need a way to create a computer generated sequence of options.
function gameStart() {
    // trying to add a timeout function to the order of the sounds generated by the loop
    // https://stackoverflow.com/questions/5226285/settimeout-in-for-loop-does-not-print-consecutive-values
    for (let i = 1; i <= 4; i++) {
        // i = setTimeout(function() {i}, 1000);
        let random = randomNumberBetween(0,3);
        if (random === 0) {
            wedge('.wedge-choice1', '#30bb0b','#008000', pickSoundGreen);
        } else if (random === 1) {
            wedge('.wedge-choice2', '#FF0000', '#B22222', pickSoundRed);
        } else if (random === 2) {
            wedge('.wedge-choice3', '#FFFF00', '#ffc303', pickSoundYellow);
        } else if (random === 3) {
            wedge('.wedge-choice4', '#0000FF', '#00008B', pickSoundBlue);
        }
      computerSequence.push(random[i]);
      console.log(random);
    }
}

// need a way for the user to enter their response
function playerAttempt() {

}